config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    member do
      get :subject_attachment
      post :add_new_attachment
    end
  end
  resources :attachments, only: [:destroy]
  resources :categories
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations'}
  get 'home/index'
  resources :users
  root to: "home#index"
  resources :articles
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :category
  has_many :articles
  has_many :attachments
  mount_uploader :image, ImageUploader

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource :find_by => :slug
  before_action :set_subject, only: [:show, :edit, :update, :destroy, :subject_attachment]
  before_action :attachment_params, only: [:add_new_attachment]

  def index
    @subjects = Subject.all
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_new_attachment
    @attachment = Attachment.create(attachment_params)
    respond_to do |format|
      format.js
    end
  end

  def subject_attachment
  end

  private

    def set_subject
      @subject = Subject.friendly.find(params[:id])
    end

    def attachment_params
      params.require(:add_new_attachment).permit(:subject_id, :title, :description, :attachment)
    end

    def subject_params
      params.require(:subject).permit(:name, :category_id, :image, :yt_link)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_attachment.html.erb
<tr id="attachment_<%= attachment.id %>">
  <td><%= attachment.title%></td>
  <td><%= link_to "Download", attachment.try(:attachment_url) %></td>
  <% if user_signed_in? %>
    <% if current_user.role == 'admin' %>
      <td><%= link_to "Delete", attachment, method: :delete, data: {confirm: 'Are You sure you want to delete this subject ?'} %></td>
    <% end %>
  <% end %>
</tr>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :youtube_link %><br>
    <%= f.text_field :yt_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/_subject_attachment.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">New Batch</h4>
    </div>
    <%= form_for :add_new_attachment, url: add_new_attachment_subject_path, remote: true,authenticity_token: true do |f| %>
      <%= f.hidden_field :subject_id, value: @subject.id%>
      <div class="modal-body">
        <div class="form-group">
          <%= f.text_field :title, class: "form-control", placeholder: "Add Title" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class: "form-control", placeholder: "Add Description" %>
        </div>
        <div class="form-group">
          <%= f.file_field :attachment %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Save Attachment", class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/subjects/add_new_attachment.js.erb
$("#attachment-modal").modal('hide')
$("#attachment-index").append("<%= escape_javascript(render('attachment', attachment: @attachment )) %>")

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.category.try(:name) %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="alert alert-success alert-dismissible custom-msg" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  Download <strong><%= @subject.name %></strong> notes.
</div>

<div class="subject-page">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <% if @subject.attachments.present? %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <th>Title</th>
              <th>Download File Link</th>
            </thead>
            <tbody id="attachment-index">
              <% @subject.attachments.each do |attachment| %>
                <tr id="attachment_<%= attachment.id %>">
                  <td><%= attachment.title%></td>
                  <td><%= link_to "Download", attachment.try(:attachment_url) %></td>
                  <% if user_signed_in? %>
                    <% if current_user.role == 'admin' %>
                      <td><%= link_to "Delete", attachment, method: :delete, data: {confirm: 'Are You sure you want to delete this subject ?'} %></td>
                    <% end %>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 col-xs-12 hidden-xs">
      <div class="invite-section">
        <iframe width="100%" height="345" src="<%= @subject.yt_link %>"></iframe>
      </div>
    </div>
  </div>
</div>
<% if user_signed_in? %>
  <% if current_user.role == 'admin' %>
    <div class="form-group">
      <%= link_to subject_attachment_subject_path(@subject), class: "btn btn-primary btn-lg", remote: true do %>
        <i class="fa fa-plus"></i> Add Attachments
      <% end %>
    </div>
    <%= link_to 'Edit', edit_subject_path(@subject) %> |
    <%= link_to 'Back', subjects_path %>
  <% end %>
<% end %>


<div class="modal fade" id="attachment-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/subjects/subject_attachment.js.erb
$("#attachment-modal").html("<%= escape_javascript(render 'subject_attachment') %>")
$("#attachment-modal").modal('show')